### PR TITLE
Changed constructors for PHP 8 Support

### PR DESCRIPTION
**Pull request by stef77dd**

### CODE REVIEW

**Comment by Neustradamus** [comment]
@stef77dd: Nice PR!

@pear team, @CloCkWeRX, @schengawegga: What do you think?

Can you enable "Issues" section too?

Thanks in advance.

**Comment by schengawegga** [comment]
I think it´s good. But i haven´t any permissions in this repository for merging this PR into master and do releases.

**Comment by Neustradamus** [comment]
@schengawegga: You must to request this list: ^^
- https://github.com/pear/Net_Sieve
- https://github.com/pear/Net_IMAP
- https://github.com/pear/Net_POP3
- https://github.com/pear/Net_LDAP
- https://github.com/pear/Net_LDAP2
- https://github.com/pear/Mail2
- https://github.com/pear/Net_SMTP2
- https://github.com/pear/Auth
- https://github.com/pear/Auth_HTTP
- https://github.com/pear/Net_LMTP
- https://github.com/pear/pear-core

**Comment by schengawegga** [comment]
@Neustradamus 😂😂 I don't have enough time to maintain all these packages

**Comment by Neustradamus** [comment]
@schengawegga: But you can help, all are linked to SCRAM, and DEPRECATED old and unsecure mechanisms ^^
- Net_Sieve is needed for Roundcube
- Mail2 is v2 of Mail
- Net_SMTP2 is v2 of Net_SMTP
- Net_IMAP must have SCRAM too: RFC9051: Internet Message Access Protocol (IMAP) - Version 4rev2: https://tools.ietf.org/html/rfc9051
- Net_LDAP must have SCRAM too: RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803
- Net_LDAP2 must have SCRAM too: RFC5803: Lightweight Directory Access Protocol (LDAP) Schema for Storing Salted: Challenge Response Authentication Mechanism (SCRAM) Secrets: https://tools.ietf.org/html/rfc5803
- Auth_HTTP must have SCRAM too: RFC7804: Salted Challenge Response HTTP Authentication Mechanism: https://tools.ietf.org/html/rfc7804
- Net_POP3 (to have compatibility too)
- Net_LMTP (to have compatibility too)
- Auth takes some parts of others
- https://github.com/search?q=repo%3Apear%2Fpear-core+cram-md5&type=code

**Comment by Neustradamus** [comment]
@schengawegga: Can you merge it?

Have you looked SCRAM parts in RFC9051?
- https://datatracker.ietf.org/doc/html/rfc9051

**Comment by Neustradamus** [comment]
@schengawegga: Can you merge it?

Have you looked SCRAM parts in RFC9051?
- https://datatracker.ietf.org/doc/html/rfc9051

Please add "Issues" section here.
Note: It will be good to add this section is other specified repositories too to track issues.

I think that the "original" @pear team members have seen your serious to improve packages :)

**Review by ashnazg — APPROVED** [review]

**Comment by Neustradamus** [comment]
@ashnazg: Can you add "Issues" section please?

At the same time, for https://github.com/pear/Net_POP3 too?

Thanks in advance.

**Pull request merged**
